/// Central configuration for app and scan versioning.
///
/// ⚠️ DO NOT EDIT THIS FILE DIRECTLY!
///
/// Instead, edit docs/version.json and run:
///   dart tools/sync_versions.dart
///
/// This keeps app, pubspec.yaml, and website in sync.
class AppConfig {
  // ============ APP VERSION ============
  // This should match pubspec.yaml version (without build number)
  // Format: MAJOR.MINOR.PATCH[-STAGE]
  // Examples: "0.5.0-dev", "0.5.0-alpha", "0.5.0-beta", "0.5.0"
  static const String appVersion = '0.4.0-dev';

  // ============ SCAN LOGIC VERSION ============
  // Simple integer - increment when classification logic changes
  // This triggers the "Rescan All?" dialog for users
  //
  // VERSION HISTORY:
  // 1  - Initial ML Kit implementation
  // 2  - Tier-based people detection, animal deduplication
  // 3  - Fixed gallery loading on fresh install
  // 4  - Stricter tier2 logic, eyelash moved to ambiguous
  // 5  - Event/party/pattern exclusions, body part detection
  // 6  - Room/furniture not documents, baby in costume → people
  // 7  - Dog requires 85%+ confidence
  // 8  - Detections store confidence, search filters low-confidence
  // 9  - Pedestrian/walker/jogger → People, 2+ clothing items → People
  // 10 - Objects need 86%+ confidence to be searchable
  static const int scanLogicVersion = 12;

  // ============ DERIVED VALUES ============
  /// Version without stage suffix (for display)
  static String get appVersionNumber {
    final parts = appVersion.split('-');
    return parts.first; // "0.5.0"
  }

  /// Stage suffix only (dev/alpha/beta or empty)
  static String get appVersionStage {
    final parts = appVersion.split('-');
    return parts.length > 1 ? parts.last : ''; // "dev", "alpha", "beta", or ""
  }

  /// Is this a dev build?
  static bool get isDev => appVersion.contains('-dev');

  /// Is this an alpha build?
  static bool get isAlpha => appVersion.contains('-alpha');

  /// Is this a beta build?
  static bool get isBeta => appVersion.contains('-beta');

  /// Is this a production build?
  static bool get isProduction => !isDev && !isAlpha && !isBeta;
}
